### PR TITLE
67 refactor and test functions of dashboarduse casespy

### PR DESCRIPTION
**Pull request by jnnchi**
The following endpoints have been fully tested and are ready to be deployed. All calculations are verified and only integer scores/values are returned (with the exception of amount spent).

Can be called through /dashboard/[ENDPOINTNAME]

Endpoint names:
      get_weekly_green_transactions/
      get_weekly_carbon_score/
      get_monthly_green_transactions/
      get_monthly_carbon_score/
      get_total_green_transactions/
      get_top_5_companies/
      get_total_co2_score/
      get_company_tiers/
      get_co2_score_change/
      get_green_transaction_change/

### CODE REVIEW

**Comment by jnnchi** [comment]
@benrockehenderson Let us know if the formatting works!

**Review by YoyoLiuuu — APPROVED** [review]
Looking good! Thank you!

**Comment by benrockehenderson** [comment]
> @benrockehenderson Let us know if the formatting works!

Almost there. I think weekly should be removed. Also, data for the line graph component should come from one endpoint.

**Comment by YoyoLiuuu** [comment]
@jnnchi can you check again to make sure the weekly is taken out and all the endpoints are merged? Thanks!

**Comment by YoyoLiuuu** [comment]
Yes! I just noticed. Thanks @benrockehenderson!

**Comment by jnnchi** [comment]
Yep, just made the changes and will make a new PR. Thanks!

**Pull request merged**
